### ISSUE TITLE
About the pre-trained model

### ISSUE THREAD

**Issue by howardgriffin** [GiannisPikoulis/dsml-thesis#1]
Hi, can you released the pretrained-model of face-reenactment. 
Thank you in advance!

**Comment by GiannisPikoulis** [comment]
Hello. 

I will try to upload the relevant `ckpt` file in the following days.

Cheers.

**Comment by howardgriffin** [comment]
Waiting for your great work！

**Comment by GiannisPikoulis** [comment]
Sorry for the delays. I'm afraid you will have to wait a bit more cause the remote compute cluster where I conducted all my experiments and saved my `ckpt` files, had to replace one of its HDDs. Probably I will be able to restore the files, but I'm not sure as to when this is going to happen. 

Sorry again for the trouble.

**Comment by GiannisPikoulis** [comment]
Hello. 

.ckpt files have been recovered. You can find them in the following [folder](https://drive.google.com/drive/folders/1qjzIprDXHqovFWT4GEgRF5OXiM--_4jC?usp=sharing).

Thanks for your patience and sorry for the delay.
